### ISSUE TITLE
Connection info

### ISSUE THREAD

**Issue by ZoomyCat** [Floobits/floobits-atom#113]
Floobits looks interesting but you're missing _key_ information in regards to connection control.

I want to know how incoming connections are managed, how you connect and how people connect to you. 

How is this done in a secure manner?

You can be sure this is not hitting my code until I am aware of what its doing... Update your info.

I see this as potential Trollsoft. What I mean by that is people deleting my lines of code without my knowledge and such.

**Comment by ggreer** [comment]
You have to give other users write permission. Even public workspaces default to read-only for other users. See also: https://floobits.com/help/faq#how_do_permissions_work

I think these sorts of questions are better served by using our [support channels](https://floobits.com/help#support) instead of creating GitHub issues.
